name: Deploy to RDP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Deployment Script
        run: |
          echo "Pulling latest code..."
          git pull origin main
          echo "Installing dependencies..."
          npm install
          echo "Restarting app..."
          npm run dev
